baseurl: ''
languageCode: en-us
title: "ğŸ“” Rough Drafts: an experiment."
googleAnalytics: ""
disqusShortname: ""
//preserveTaxonomyNames: true
footnotereturnlinkcontents: â†©
disableHugoGeneratorInject: true
pluralizeListTitles: false
pygmentsCodeFences: false
pygmentsUseClasses: false
minify: true

permalinks:
  writing: /writing/:slug/
  projects: /projects/:slug/

menu:
  main:
    - name: "ğŸ  Home"
      url: "/"
      weight: 1
    - name: "â“ About"
      url: "/about/"
      weight: 2
    - name: "âœï¸ Writing"
      url: "/writing/"
      weight: 3
    - identifier: projects
      name: "âœ¨ Projects"
      url: /projects/
      weight: 4
    - name: "ğŸ·ï¸ Tags"
      url: "/tags/"
      weight: 5

params:
  description: "Jam is a minimal personal blog and portfolio theme powered by Hugo."

frontmatter:
  author: B. Kenneth Brown
  github: 'https://github.com/brennanbrown'
  facebook: 'https://facebook.com/brennankbrown'
  og_image: /images/####
  sitename: ######
  twitter: 'https://twitter.com/bkennethbrown'

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom


